name: Docker-Pipeline

on:
  push:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to Docker
        id: build-image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "${{ steps.login-ecr.outputs.registry }}/new:${{ github.sha }}"
          context: "."
          build-args: "FUNCTION_DIR=a,FUNCTION_DIR2=b"

      - id: versions
        run: |
          docker run --rm ${{ steps.login-ecr.outputs.registry }}/new:${{ github.sha }}